### ISSUE TITLE
New translations: Dark stage & score screen

### ISSUE THREAD

**Issue by alexheretic** [big-ab-games/robo-instructus-translation#18]
@MaelColuim @raspy @ozkriff @ToastShaman @lukasz81 @narimanp @lewapro @andcoe 

I've updated google translations for the following new pairs. If you have a few minutes can you check out your native versions and see if they make sense?

## _ru examples_

```
#### "Dark Stages" are the name of level stages that have totally hidden details
Dark Stage
Темная сцена
```
![](https://user-images.githubusercontent.com/2331607/59873230-72fa6980-9393-11e9-8f8e-d9e746f75e3a.jpg)

```
### Score screen
#### explanation of "Time" score
Sum of function call runtimes & environmental delays
Сумма времени выполнения вызова функции

#### explanation of "Solution size" score
Number of distinct evaluated code phrases
Количество различных оцененных кодовых фраз

#### explanation of "Run size" score
Total number of evaluated code phrases
Общее количество оцененных кодовых фраз
```
![](https://user-images.githubusercontent.com/2331607/59873314-9f15ea80-9393-11e9-8589-f9176104b37d.jpg)
```
Dark stages are similar to the others\nbut their details are hidden
Темные сцены похожи на другие, но их детали скрыты

Ensure your solution is general enough\nto solve these hidden variants
Убедитесь, что ваше решение достаточно общее,\nчтобы решить эти скрытые варианты
```
![](https://user-images.githubusercontent.com/2331607/59873331-a63cf880-9393-11e9-9046-7606b3741c75.jpg)

**Comment by ozkriff** [comment]
LGTM, except for

> Sum of function call runtimes & environmental delays
> Сумма времени выполнения вызова функции

I'd translate that as something like "Общее время выполнения вызовов функций и задержек окружения"?
