### ISSUE TITLE
company messages: english

### ISSUE THREAD

**Issue by lgb** [big-ab-games/robo-instructus-translation#53]
I think whole paragraph in one line is may be little hard to check and understand differences (in history). How about split every paragraph to lot of lines, by one sentence per line?

It's available case for MarkDown and usually trick for wikies.

**Comment by alexheretic** [comment]
The game's markup doesn't support that as it isn't a full markdown thing, just a custom simple markup I made for the game.

I think paragraphs are workable as is, you can still see word diffs.

**Comment by lgb** [comment]
It's still usable of course, but long lines isn't very convenient in default toolset.

![image](https://user-images.githubusercontent.com/153921/63390617-68bb1280-c3b8-11e9-9e6e-e359b850ecec.png)
![image](https://user-images.githubusercontent.com/153921/63390724-c0f21480-c3b8-11e9-9ddd-c4a8220c16a7.png)

**Comment by alexheretic** [comment]
Yes I agree it isn't ideal. But as the game's markup is not proper markdown, so does not ignore single newlines, this trick won't work without changes to the game code.

Right now I don't think it worth looking into those game code changes for the sake of improving the diffs. Hopefully this won't be too annoying for you and others during translation.

Also the diff tools _can_ show these up better, for example my `git diff` & github's web diff seem to. 
![](https://user-images.githubusercontent.com/2331607/63425660-f888ad00-c408-11e9-90e4-8edeabee3ce9.png)
It's possible your diff tools can be configured similarly.
