### ISSUE TITLE
long strings in code samples

### ISSUE THREAD

**Issue by lgb** [big-ab-games/robo-instructus-translation#66]
It's in "test" branch with russian translation. Comment in example for "for" loop is too long - it corrupt the debug view.

I can change this comment, but there are may another places with same issue (maybe in another languages).

Can you check it automatical-way? Or increase the width for code examples? Or add horizontal scrolling? Or change height of block in this case....

![image](https://user-images.githubusercontent.com/153921/64572107-b7801a80-d36e-11e9-9b62-fb3b144c60e2.png)
![image](https://user-images.githubusercontent.com/153921/64572198-07f77800-d36f-11e9-8b53-8c7d6fd0a42f.png)

**Comment by alexheretic** [comment]
Good spot, this is a limitation with how they're rendered currently. I'll take a look tomorrow to see if I can make it more rugged.

**Comment by alexheretic** [comment]
I've pushed a fix that will support comment wrapping properly. That should fix this issue.

There can still be some related issues at some window sizes if the inline debugging output wraps, but it's less obvious to me a good workaround & it's also less likely to happen in these examples.
