### ISSUE TITLE
Fullscreen glitches

### ISSUE THREAD

**Issue by HSteinway** [big-ab-games/robo-instructus-translation#95]
When I enter the game, some keys are slightly cut from below and from the right side (attached). Then I turn FS off and the window becomes (attached)! If I manage to click on 'Fullscreen On' again on this little one, everything is fine. Win7, NVidia GTX 1660, 1080 x 1920.
![image](https://user-images.githubusercontent.com/58853753/71492483-87d71e80-2848-11ea-9996-6b1444109ebd.png)
![image](https://user-images.githubusercontent.com/58853753/71492506-ba811700-2848-11ea-981f-847bb3ac2678.png)

**Comment by HSteinway** [comment]
After that. It's OK.
![image](https://user-images.githubusercontent.com/58853753/71492612-9f62d700-2849-11ea-83ca-54b28fff47fa.png)

**Comment by alexheretic** [comment]
Thanks for the report. Is this happening every time you start the game?

**Comment by HSteinway** [comment]
> Thanks for the report. Is this happening every time you start the game?

Not every time. 49% approx.)

**Comment by alexheretic** [comment]
Ok, I'll try to reproduce it when I'm near my windows system again.

**Comment by HSteinway** [comment]
I just realized that it happens just the first time I start the game after reboot. I can't replicate the glitch. =\

**Comment by alexheretic** [comment]
This _should_ be fixed by the 1.23 update which updates the underlying window library and resize event handling.
